version: '3.1'

services:
  app:
    build: ./
    ports:
      - 3000:3000
    networks:
      - local
    depends_on:
      - pg_db
    volumes:
      - ./:/app
    environment:
      WAIT_HOSTS: pg_db:5432
  pg_db:
    container_name: pg_db
    image: postgres
    restart: always
    networks:
      - local
    ports:
      - 5432:5432
    volumes:
      - ./.docker/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: test

networks:
  local: